# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z40JFq_TPPDZRPyXyWiLD4mF_ULsaKzU
"""

import streamlit as st
import pickle
import pandas as pd

import requests

def fetch_posters(movie_id):
    response=requests.get('https://api.themoviedb.org/3/movie/{}?api_key=06c88b624faad94a0bcb2e9b59538063'.format(movie_id))
    data=response.json()
    print(data)
    return "https://image.tmdb.org/t/p/original" + data['poster_path']

# Load data
movies = pickle.load(open('movies.pkl', 'rb'))  # DataFrame
similarity = pickle.load(open('similarity.pkl', 'rb'))  # similarity matrix


def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    recommended_movies = []
    recommended_movies_posters=[]
    for i in movies_list:
        movie_id=movies.iloc[i[0]].movie_id

        recommended_movies.append(movies.iloc[i[0]].title)
        # fetch poster using API
        # 06c88b624faad94a0bcb2e9b59538063
        recommended_movies_posters.append(fetch_posters(movie_id))
    return recommended_movies, recommended_movies_posters


st.title('Movie Recommender System')

selected_movie_name = st.selectbox(
    'What do you want to watch?',
    movies['title'].values
)

if st.button('Recommend'):
    recommended_movies, recommended_movies_posters = recommend(selected_movie_name)
    cols = st.columns(5)
    for idx, col in enumerate(cols):
        col.text(recommended_movies[idx])
        col.image(recommended_movies_posters[idx])